# Define the name of the workflow
name: Deploy my Lambda Function

on:
  push:
    branches:
      - main
# Five steps of the job
jobs:
# Job name is 'build'
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Check out code
      uses: actions/checkout@v2
    - name: Step 2 - set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Step 3 - Install library
      run: |
        cd function
        python -m pip install --upgrade pip
        if [ -f requiremetns.txt]; then pip install -r requirements.txt -t .; fi
    - name: Step 4 - Create zip bundle
      run: |
        cd function
        zip -r ../${{github.sha}}.zip .
    - name: Step 5 - Archieve artifact
      uses: actions/upload-artifact@v2
      with:
        name: zipped-bundle
        path: ${{github.sha}}.zip
        
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: zipped-bundle
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
      # Use the repo secret stored in GitHub repo
        aws-access-key-id: $ {{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: Upload to S3
      run: aws s3 cp ${{github.sha}}.zip s3://s3-bucket-123123123/${{github.sha}}.zip
        
    
      
